spring.application.name=auth-service
server.port=8081

# Postgres (ajuste user/password/database)
spring.datasource.url=jdbc:postgresql://localhost:5432/auth_service
spring.datasource.username=postgres
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT
jwt.secret=3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b6c4b8f6d9e2c5a3b7f1d4e8c9a2b5d3e7f0a6c8b4d1e9f7a3c5b8d2e6f4a0c9
jwt.expiration-ms=3600000
jwt.refresh-expiration-days=30

# OpenAPI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
#http://localhost:8081/swagger-ui.html

# MFA
app.name=Auth Service